global:
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'your_username'
  smtp_auth_password: 'your_password'

route:
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'your_email@example.com'
